
version: 2.1

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    
    parameters:
      com:
        type: string
        default: ""
      msg:
        type: string
        default: ""

    # echo << parameters.env >>
    # << parameters.env >>
    steps:
      - checkout
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            # echo "tests ########"
            # echo << parameters.env >>
            cd tests
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
            # pytest -v -s
            << parameters.com >>
            


workflows:
  # version: 2

  build-deploy:
    when:
      equal: [ "every_min", << pipeline.schedule.name >> ]
    jobs:
      - build-and-test:
          name: job-1
          com: pytest -v -s
          msg: "run job-1"
      - build-and-test:
          name: job-2
          # requires:
          #   - job-1
          com: pytest -v -s # "pytest -v -s requirements.txt"
          msg: "run job-2"
      - build-and-test:
          name: job-3
          # requires:
          #   - job-2
          com: pytest -v -s
          msg: "run job-3"



    # jobs:
    #   - build-and-test:
    #       name: job-1-<< matrix.env >>
    #       matrix:
    #         parameters:
    #           env: [
    #             "num1", 
    #             "num2", 
    #             "num3"
    #             ]

    #   - build-and-test:
    #       name: job-2-<< matrix.env >>
    #       matrix:
    #         parameters:
    #           env: [
    #             "num4", 
    #             "num5", 
    #             "num6"
    #             ]


