
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    
    parameters:
      env:
        type: string
        default: "development"
      reg:
        type: string
        default: "us"
    steps:
      - checkout
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            echo "tests ########"
            cd tests
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
            pytest -v -s


workflows:
  version: 2

  commit:
    jobs:
      - build-and-test:
        env: dev
        reg: aws



  # my_workflow: 
  #   triggers:
  #     - schedule:
  #         cron: "*/5 * * * *"
    # when:
    #   equal: [ "every_min", << pipeline.schedule.name >> ]
    # jobs:
    #   - build-and-test
