
version: 2.1

jobs:
  run-api-tests: 
    docker:
      - image: cimg/python:3.10.2
    
    parameters:
      cmd:
        type: string
        default: ""
      msg:
        type: string
        default: ""
      env:
        type: string
        default: ""
      reg:
        type: string
        default: ""

    steps:
      - checkout
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            echo << parameters.cmd >>
            cd tests
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
            # pytest -v -s
            << parameters.cmd >>
            


workflows:
  # version: 2

  api-tests:
    when:
      equal: [ "every_min", << pipeline.schedule.name >> ]
    jobs:
      - run-api-tests:
          name: job-name-1
          cmd: pytest -v -s
          msg: run job-1
          
      - run-api-tests:
          name: job-name-2
          cmd: pytest -v -s
          msg: run job-2
          
      - run-api-tests:
          name: job-name-3
          requires:
            - job-name-2
          cmd: pytest -v -s
          msg: run job-3






    # jobs:
    #   - build-and-test:
    #       name: job-1-<< matrix.env >>
    #       matrix:
    #         parameters:
    #           env: [
    #             "num1", 
    #             "num2", 
    #             "num3"
    #             ]

    #   - build-and-test:
    #       name: job-2-<< matrix.env >>
    #       matrix:
    #         parameters:
    #           env: [
    #             "num4", 
    #             "num5", 
    #             "num6"
    #             ]


