
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            cd tests
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip3 install wheel
            pip3 install -r requirements.txt
            pytest -v -s


workflows:
  version: 2

  my_workflow: 
    triggers:
      - schedule:
          cron: "*/5 * * * *"
    # when:
    #   equal: [ "every_min", << pipeline.schedule.name >> ]
    # jobs:
    #   - build-and-test
