
version: 2.1

# parameters:
#   test_env:
#     default: dev
#     type: string

#   test_reg:
#     default: aws
#     type: string

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    
    parameters:
      env:
        type: string
        default: ""

    # echo << parameters.env >>
    steps:
      - checkout
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            echo "tests ########"
            cd tests
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
            << parameters.env >>


# workflows:
#   # version: 2

#   build-deploy:
#     when:
#       equal: [ "every_min", << pipeline.schedule.name >> ]
#     jobs:
#       - build-and-test:
#           env: "pytest -v -s"
#       - build-and-test:
#           requires:
#             - build-and-test
#           env: "pytest -v -s"
#       - build-and-test:
#           requires:
#             - build-and-test
#           env: "pytest -v -s"




  # my_workflow: 
  #   triggers:
  #     - schedule:
  #         cron: "*/5 * * * *"
    # when:
    #   equal: [ "every_min", << pipeline.schedule.name >> ]
    # jobs:
    #   - build-and-test
